# Generated by Django 5.2.7 on 2026-03-31 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razorpay_order_id", models.CharField(db_index=True, max_length=100)),
                (
                    "razorpay_payment_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("razorpay_signature", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(default="captured", max_length=30)),
                (
                    "payment_method",
                    models.CharField(blank=True, default="razorpay", max_length=50),
                ),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
