# Generated by Django 5.2.7 on 2026-03-27 12:40

import django.db.models.deletion
import users.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StaffInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("ADMIN", "Admin"),
                            ("STAFF", "Staff"),
                            ("CUSTOMER", "Customer"),
                        ],
                        default="STAFF",
                        max_length=20,
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "invited_by_global_user_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(default=users.models.invite_default_expiry),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["token"], name="users_staff_token_50c7ca_idx"),
                    models.Index(fields=["email"], name="users_staff_email_6f5a12_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SubjectMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("global_user_id", models.BigIntegerField(db_index=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("ADMIN", "Admin"),
                            ("STAFF", "Staff"),
                            ("CUSTOMER", "Customer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["global_user_id", "role"],
                        name="users_subje_global__f03bfc_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("global_user_id",),
                        name="uniq_tenant_member_global_user",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Coordinate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("house_no", models.CharField(max_length=255)),
                ("landmark", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("work", "Work"),
                            ("office", "Office"),
                            ("other", "Other"),
                        ],
                        default="home",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="users.subjectmember",
                    ),
                ),
            ],
        ),
    ]
