# Generated by Django 5.2.7 on 2026-02-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_delete_tenantmember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinate",
            name="is_default",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="subjectmember",
            name="email",
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AddConstraint(
            model_name="subjectmember",
            constraint=models.UniqueConstraint(
                fields=("email",), name="uniq_subjectmember_email"
            ),
        ),
    ]
