# Generated by Django 5.2.7 on 2025-11-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
    migrations.AddField(
        model_name='loginsession',
        name='session_key',
        field=models.CharField(max_length=40, null=True, blank=True, db_index=True),
    ),
]

