# Generated by Django 5.2.7 on 2026-03-16 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Backup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("tenant", "Tenant"), ("global", "Global")],
                        default="tenant",
                        max_length=10,
                    ),
                ),
                (
                    "tenant_schema",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("file_path", models.CharField(blank=True, max_length=1024, null=True)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BackupLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "level",
                    models.CharField(
                        choices=[("INFO", "Info"), ("ERROR", "Error")],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "backup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="backups.backup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backup Log",
                "verbose_name_plural": "Backup Logs",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="GlobalBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("retention_weeks", models.PositiveIntegerField(default=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "backup",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_meta",
                        to="backups.backup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Global Backup Metadata",
                "verbose_name_plural": "Global Backups",
                "ordering": ["-created_at"],
            },
        ),
    ]
