# Generated by Django 5.2.8 on 2026-01-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='backup',
            table=None,
        ),
        migrations.AlterModelTable(
            name='backuplog',
            table=None,
        ),
        migrations.AlterModelTable(
            name='globalbackup',
            table=None,
        ),
    ]
