# Generated by Django 5.2.7 on 2025-12-10 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backupalert",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
