# Generated by Django 5.2.7 on 2025-12-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backups", "0002_alter_backupalert_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="backupalert",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
