# Generated by Django 5.2.7 on 2025-12-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backups", "0003_backupalert_completed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_name", models.CharField(max_length=255)),
                ("backup_type", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=10)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Backup Failure",
                "verbose_name_plural": "Backup Failures",
                "db_table": "backup_failure_log",
                "ordering": ["-timestamp"],
            },
        ),
    ]
