# Generated by Django 5.2.7 on 2026-03-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backups", "0004_backupfailure"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BackupFailure",
        ),
    ]
