# Generated by Django 5.2.7 on 2026-03-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0004_backupfailure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupFailure',
        ),
    ]
