# Generated by Django 5.2.7 on 2026-01-01 15:23

import django.db.models.deletion
import django.utils.timezone
import django_tenants.postgresql_backend.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
<<<<<<< HEAD
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                ("tenant_name", models.CharField(max_length=100)),
                (
                    "server_name",
                    models.CharField(
                        help_text="VPS or server identifier", max_length=150
                    ),
                ),
                (
                    "desired_domain",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("company", models.CharField(blank=True, max_length=200, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tenant_logos/"),
                ),
                (
                    "theme",
                    models.CharField(
                        default="default",
                        help_text="Theme or template name for the tenant",
                        max_length=50,
                    ),
                ),
                ("has_used_trial", models.BooleanField(default=False)),
                ("storage_used_mb", models.FloatField(default=0.0)),
                ("product_count", models.IntegerField(default=0)),
                ("order_count", models.IntegerField(default=0)),
                ("visitor_count_7d", models.IntegerField(default=0)),
                ("visitor_count_30d", models.IntegerField(default=0)),
                ("active_users", models.IntegerField(default=0)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('tenant_name', models.CharField(max_length=100)),
                ('server_name', models.CharField(help_text='VPS or server identifier', max_length=150)),
                ('desired_domain', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/')),
                ('storage_used_mb', models.FloatField(default=0.0)),
                ('product_count', models.IntegerField(default=0)),
                ('order_count', models.IntegerField(default=0)),
                ('visitor_count_7d', models.IntegerField(default=0)),
                ('visitor_count_30d', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
<<<<<<< HEAD
                ('paid_until', models.DateField(blank=True, null=True)),
                ('on_trial', models.BooleanField(default=True)),
                ('created_on', models.DateField(auto_now_add=True)),
>>>>>>> defaf09 (subscription and billing integration(razorpay) changed from billing app to customers app)
=======
>>>>>>> 69fec36 (Razorpay Integration)
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name="PlanPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("duration_days", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="RzpWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=80)),
                ("payload", models.JSONField()),
                ("signature_ok", models.BooleanField(default=False)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("basic", "Basic"),
                            ("standard", "Standard"),
                            ("premium", "Premium"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("storage_limit_mb", models.PositiveIntegerField(default=500)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("auto_renew", models.BooleanField(default=False)),
                (
                    "manual_override",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, admin can manually modify subscription dates or status.",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.client",
                    ),
                ),
                (
                    "pricing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="customers.planpricing",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customers.subscriptionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-end_date"],
            },
        ),
        migrations.CreateModel(
            name="Domain",
=======
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> 69fec36 (Razorpay Integration)
            name='RzpInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('amount_in_paise', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RzpPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=50, unique=True)),
                ('interval', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('amount_in_paise', models.PositiveIntegerField(help_text='100.00 INR → 10000 paise')),
                ('razorpay_plan_id', models.CharField(blank=True, help_text='Maps to an existing RZP plan if needed', max_length=64, null=True)),
                ('features', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='RzpWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=80)),
                ('payload', models.JSONField()),
                ('signature_ok', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('storage_limit_mb', models.PositiveIntegerField(default=500)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('method', models.CharField(choices=[('COD', 'Cash On Delivery'), ('UPI', 'UPI'), ('CARD', 'Credit/Debit Card')], max_length=20)),
                ('payment_plan', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=20)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientRefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_type', models.CharField(choices=[('product_issue', 'Product/Service Issue'), ('late_delivery', 'Late Delivery'), ('payment_error', 'Payment Error'), ('duplicate_payment', 'Duplicate Payment'), ('subscription_cancel', 'Subscription Cancellation'), ('others', 'Others')], max_length=50)),
                ('refund_policy', models.CharField(choices=[('full', 'Full Refund'), ('partial', 'Partial Refund'), ('no_refund', 'No Refund')], default='partial', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('reason', models.TextField()),
                ('terms_and_conditions', models.TextField(default='Refund requests must comply with the platform’s current policy and can be rejected if criteria are not met.')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_refunded', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('policy_version', models.CharField(default='v1.0', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.clientpayment')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('grace_period_days', models.PositiveIntegerField(default=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='active', max_length=15)),
                ('auto_renew', models.BooleanField(default=False)),
                ('manual_override', models.BooleanField(default=False, help_text='Allow admin to manually override date or status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='customers.clientpayment')),
                ('payment_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_references', to='customers.clientpayment')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('invoice_type', models.CharField(choices=[('manual', 'Manually Generated'), ('auto', 'Auto Generated')], default='auto', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.clientpayment')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.clientsubscription')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='customers.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=20, unique=True)),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manually Generated"),
                            ("auto", "Auto Generated"),
                        ],
                        default="auto",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Issued"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="issued",
                        max_length=10,
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("currency", models.CharField(default="INR", max_length=10)),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customers.client",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customers.clientsubscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RzpPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("amount", models.PositiveIntegerField()),
                ("currency", models.CharField(default="INR", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("authorized", "Authorized"),
                            ("captured", "Captured"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("payment.created", "Payment Created"),
                            ("payment.authorized", "Payment Authorized"),
                            ("payment.captured", "Payment Captured"),
                            ("payment.failed", "Payment Failed"),
                            ("refund.processed", "Refund Processed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("captured", models.BooleanField(default=False)),
                ("failure_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="customers.invoice",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="customers.clientsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RzpRefund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razorpay_refund_id", models.CharField(max_length=64, unique=True)),
                ("amount_in_paise", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunded_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="customers.rzppayment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="planpricing",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.subscriptionplan",
            ),
        ),
        migrations.CreateModel(
            name="TenantRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_name", models.CharField(max_length=100)),
                ("desired_domain", models.CharField(max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("company", models.CharField(blank=True, max_length=200, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tenant_logos/"),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("minimal", "Minimal"),
                            ("modern", "Modern"),
                        ],
                        default="default",
                        max_length=50,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("requested_on", models.DateField(default=django.utils.timezone.now)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("trial_created", "Trial Created"),
                            ("paid_created", "Paid Created"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="Pending_payment",
                        max_length=20,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="customers.subscriptionplan",
                    ),
                ),
                (
                    "pricing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="customers.planpricing",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="invoice",
            name="tenant_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="customers.tenantrequest",
            ),
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "Technical Issue"),
                            ("billing", "Billing"),
                            ("general", "General Query"),
                            ("feature", "Feature Request"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=50,
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="customers.client",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="rzppayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("razorpay_payment_id__isnull", False)),
                fields=("razorpay_payment_id",),
                name="uniq_rzp_payment_id__nonnull",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="planpricing",
            unique_together={("plan", "billing_cycle")},
        ),
        migrations.AddConstraint(
            model_name="tenantrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["pending_payment", "trial_created", "paid_created"])
                ),
                fields=("desired_domain",),
                name="uniq_reserved_domain_active_requests",
            ),
        ),
    ]
