# Generated by Django 5.2.7 on 2026-03-10 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpayOrderMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("local_order_id", models.PositiveBigIntegerField()),
                ("local_order_number", models.CharField(blank=True, max_length=50)),
                (
                    "razorpay_order_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("amount_paise", models.PositiveIntegerField()),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("receipt", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(default="created", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.client",
                    ),
                ),
            ],
        ),
    ]
