# Generated by Django 5.2.7 on 2025-12-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="brand_color",
            field=models.CharField(default="#2563eb", max_length=20),
        ),
        migrations.AddField(
            model_name="client",
            name="theme",
            field=models.CharField(
                default="default",
                help_text="Theme or template name for the tenant",
                max_length=50,
            ),
        ),
    ]
