# Generated by Django 5.2.7 on 2025-11-05 13:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantrequest',
            name='requested_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
