# Generated by Django 5.2.8 on 2025-12-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='brand_color',
            field=models.CharField(blank=True, default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='theme',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
    ]
