# Generated by Django 5.2.7 on 2025-11-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantrequest',
            name='payment_plan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tenantrequest',
            name='payment_mode',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('UPI', 'UPI'), ('CARD', 'Credit/Debit Card')], default='COD', max_length=10),
        ),
        migrations.AlterField(
            model_name='tenantrequest',
            name='plan_type',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], default='Basic', max_length=50),
        ),
    ]
