<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-12-05 10:51
=======
# Generated by Django 5.2.8 on 2025-12-09 12:48
>>>>>>> 304533d (cleaned the unwanted files and folders)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("customers", "0001_initial"),
=======
        ('customers', '0001_initial'),
>>>>>>> 304533d (cleaned the unwanted files and folders)
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name="client",
            name="brand_color",
            field=models.CharField(default="#2563eb", max_length=20),
        ),
        migrations.AddField(
            model_name="client",
            name="theme",
            field=models.CharField(
                default="default",
                help_text="Theme or template name for the tenant",
                max_length=50,
            ),
=======
            model_name='client',
            name='brand_color',
            field=models.CharField(blank=True, default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='theme',
            field=models.CharField(blank=True, default='default', max_length=50),
>>>>>>> 304533d (cleaned the unwanted files and folders)
        ),
    ]
