# Generated by Django 5.2.7 on 2026-01-02 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rzpwebhookevent",
            old_name="received_at",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="rzppayment",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="rzppayment",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="customers.clientsubscription",
            ),
        ),
    ]
