# Generated by Django 5.2.7 on 2025-12-16 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rzppayment",
            old_name="amount_in_paise",
            new_name="amount",
        ),
    ]
