# Generated by Django 5.2.8 on 2025-12-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_client_brand_color_client_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='rzpsubscription',
            name='brand_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='rzpsubscription',
            name='theme',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='tenantrequest',
            name='brand_color',
            field=models.CharField(blank=True, default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantrequest',
            name='theme',
            field=models.CharField(blank=True, default='default', max_length=50),
        ),
    ]
