# Generated by Django 5.2.9 on 2026-01-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_rzppayment_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='product_mode',
            field=models.CharField(blank=True, choices=[('single', 'Single Product'), ('multi', 'Multi Product')], max_length=10, null=True),
        ),
    ]
