# Generated by Django 5.2.7 on 2026-01-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_rename_received_at_rzpwebhookevent_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
