# Generated by Django 5.2.7 on 2025-11-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_client_address_client_company_client_email_and_more"),
        ("customers", "0002_tenantrequest_is_approved_tenantrequest_requested_on"),
    ]

    operations = []
