# Generated by Django 5.2.7 on 2025-12-17 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_amount_in_paise_rzppayment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='brand_color',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='tenantrequest',
            name='payment_mode',
        ),
        migrations.AddField(
            model_name='client',
            name='has_used_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantrequest',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('minimal', 'Minimal'), ('modern', 'Modern')], default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('free_trial', 'Free Trial'), ('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='PlanPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('trial', 'Free Trial'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_days', models.PositiveIntegerField()),
                ('is_trial', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.subscriptionplan')),
            ],
            options={
                'unique_together': {('plan', 'billing_cycle')},
            },
        ),
        migrations.AddField(
            model_name='clientsubscription',
            name='pricing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.planpricing'),
        ),
    ]
