# Generated by Django 5.2.7 on 2025-11-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_tenantrequest_payment_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantrequest',
            name='payment_plan',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Monthly', max_length=10),
        ),
    ]
