# Generated by Django 5.2.7 on 2025-11-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_tenantrequest_payment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantrequest',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
