# Generated by Django 5.2.7 on 2026-01-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_alter_tenantrequest_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="has_used_trial",
        ),
        migrations.AddField(
            model_name="client",
            name="used_trial",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Indicates if the tenant has used their trial period",
            ),
        ),
    ]
