# Generated by Django 5.2.7 on 2025-12-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_fixed_tenantrequest_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantrequest",
            name="is_trail",
            field=models.BooleanField(default=False),
        ),
    ]
