# Generated by Django 5.2.7 on 2025-11-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_tenantrequest_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantrequest',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
