# Generated by Django 5.2.7 on 2026-01-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_remove_client_has_used_trial_client_used_trial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenantrequest",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="client",
            name="owner_name",
            field=models.CharField(default="Owner", max_length=100),
        ),
        migrations.AddField(
            model_name="tenantrequest",
            name="owner_name",
            field=models.CharField(default="Owner", max_length=100),
        ),
    ]
