# Generated by Django 5.2.7 on 2026-01-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customers",
            "0005_remove_tenantrequest_is_approved_client_owner_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="server_name",
        ),
        migrations.AlterField(
            model_name="client",
            name="owner_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tenantrequest",
            name="owner_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
