# Generated by Django 5.2.7 on 2025-12-24 18:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_tenantrequest_is_trail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientsubscription",
            options={},
        ),
        migrations.RemoveField(
            model_name="clientsubscription",
            name="auto_renew",
        ),
        migrations.RemoveField(
            model_name="clientsubscription",
            name="client",
        ),
        migrations.RemoveField(
            model_name="clientsubscription",
            name="manual_override",
        ),
        migrations.RemoveField(
            model_name="clientsubscription",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="clientsubscription",
            name="pricing",
        ),
        migrations.AddField(
            model_name="clientsubscription",
            name="billing_cycle",
            field=models.CharField(
                blank=True,
                choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="clientsubscription",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clientsubscription",
            name="razorpay_payment_link_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="clientsubscription",
            name="razorpay_payment_link_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientsubscription",
            name="tenant",
            field=models.OneToOneField(
                default=-2013,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to="customers.client",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clientsubscription",
            name="trial_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientsubscription",
            name="trial_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clientsubscription",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customers.subscriptionplan",
            ),
        ),
        migrations.AlterField(
            model_name="clientsubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("trial", "Trial"),
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("suspended", "Suspended"),
                    ("payment_pending", "Payment Pending"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tenantrequest",
            name="payment_plan",
            field=models.CharField(
                blank=True,
                choices=[("Monthly", "Monthly"), ("Yearly", "Yearly")],
                max_length=20,
                null=True,
            ),
        ),
    ]
