# Generated by Django 5.2.7 on 2025-12-24 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_alter_clientsubscription_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientsubscription",
            options={"ordering": ["-end_date"]},
        ),
        migrations.RemoveField(
            model_name="clientsubscription",
            name="billing_cycle",
        ),
        migrations.RemoveField(
            model_name="clientsubscription",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="clientsubscription",
            name="razorpay_payment_link_id",
        ),
        migrations.RemoveField(
            model_name="clientsubscription",
            name="razorpay_payment_link_url",
        ),
        migrations.RemoveField(
            model_name="clientsubscription",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="clientsubscription",
            name="trial_end",
        ),
        migrations.RemoveField(
            model_name="clientsubscription",
            name="trial_start",
        ),
        migrations.RemoveField(
            model_name="tenantrequest",
            name="is_trail",
        ),
        migrations.AddField(
            model_name="clientsubscription",
            name="auto_renew",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clientsubscription",
            name="client",
            field=models.ForeignKey(
                default=-2013,
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.client",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clientsubscription",
            name="manual_override",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, admin can manually modify subscription dates or status.",
            ),
        ),
        migrations.AddField(
            model_name="clientsubscription",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customers.payment",
            ),
        ),
        migrations.AddField(
            model_name="clientsubscription",
            name="pricing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="customers.planpricing",
            ),
        ),
        migrations.AlterField(
            model_name="clientsubscription",
            name="plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customers.subscriptionplan",
            ),
        ),
        migrations.AlterField(
            model_name="clientsubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("suspended", "Suspended"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="tenantrequest",
            name="payment_plan",
            field=models.CharField(
                choices=[("Monthly", "Monthly"), ("Yearly", "Yearly")],
                default="Monthly",
                max_length=10,
            ),
        ),
    ]
