# Generated by Django 5.2.7 on 2026-01-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_remove_client_server_name"),
        (
            "customers",
            "0006_remove_client_server_name_alter_client_owner_name_and_more",
        ),
    ]

    operations = []
