# Generated by Django 5.2.7 on 2025-12-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0007_alter_clientsubscription_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planpricing",
            name="is_trial",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="is_trial",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="price",
        ),
        migrations.AlterField(
            model_name="planpricing",
            name="billing_cycle",
            field=models.CharField(
                choices=[
                    ("trial", "Trial"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                max_length=10,
            ),
        ),
    ]
