# Generated by Django 5.2.7 on 2025-12-25 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0008_remove_planpricing_is_trial_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenantrequest",
            name="payment_plan",
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_plan",
            field=models.CharField(
                choices=[("Monthly", "Monthly"), ("Yearly", "Yearly")],
                default="Monthly",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="name",
            field=models.CharField(
                choices=[
                    ("trial", "Trial"),
                    ("basic", "Basic"),
                    ("standard", "Standard"),
                    ("premium", "Premium"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenantrequest",
            name="pricing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="customers.clientsubscription",
            ),
        ),
    ]
