# Generated by Django 5.2.7 on 2025-12-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0009_remove_tenantrequest_payment_plan_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenantrequest",
            name="pricing",
        ),
    ]
