# Generated by Django 5.2.7 on 2025-12-25 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0011_tenantrequest_pricing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantrequest",
            name="pricing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="customers.planpricing",
            ),
        ),
    ]
