# Generated by Django 5.2.7 on 2025-12-26 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0012_alter_tenantrequest_pricing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refundrequest",
            name="payment",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="customers.rzppayment"
            ),
        ),
        migrations.RemoveField(
            model_name="clientsubscription",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="refundrequest",
            name="client",
        ),
        migrations.AlterModelOptions(
            name="rzppayment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="rzppayment",
            name="invoice",
        ),
        migrations.AddField(
            model_name="rzppayment",
            name="event",
            field=models.CharField(
                blank=True,
                choices=[
                    ("payment.created", "Payment Created"),
                    ("payment.authorized", "Payment Authorized"),
                    ("payment.captured", "Payment Captured"),
                    ("payment.failed", "Payment Failed"),
                    ("refund.processed", "Refund Processed"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="rzppayment",
            name="failure_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rzppayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("authorized", "Authorized"),
                    ("captured", "Captured"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="planpricing",
            name="duration_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="rzppayment",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="RefundRequest",
        ),
    ]
