# Generated by Django 5.2.7 on 2026-02-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleproduct',
            name='featured_order',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Position in homepage banner (1–3)', null=True),
        ),
        migrations.AddField(
            model_name='singleproduct',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singleproductimage',
            name='image_type',
            field=models.CharField(choices=[('product', 'Product Image'), ('banner', 'Banner Image')], default='product', max_length=10),
        ),
    ]
