# Generated by Django 5.2.9 on 2026-01-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_multicategory_varianttype_multiproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleproduct',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
