# Generated by Django 5.2.9 on 2026-01-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_singleproduct_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiproduct',
            name='availability',
            field=models.BooleanField(default=False),
        ),
    ]
