# Generated by Django 5.2.9 on 2026-01-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_multiproduct_availability'),
    ]

    operations = [
    ]
