# Generated by Django 5.2.7 on 2026-03-16 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant", models.CharField(default="default_tenant", max_length=100)),
                ("customer_email", models.EmailField(default="", max_length=254)),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "subtotal_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "shipping_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "shipping_full_name",
                    models.CharField(default="Not Provided", max_length=255),
                ),
                (
                    "shipping_phone",
                    models.CharField(default="Not Provided", max_length=20),
                ),
                (
                    "shipping_house_no",
                    models.CharField(default="Not Provided", max_length=100),
                ),
                (
                    "shipping_landmark",
                    models.CharField(default="Not Provided", max_length=100),
                ),
                ("shipping_address", models.TextField(default="Not Provided")),
                (
                    "shipping_city",
                    models.CharField(default="Not Provided", max_length=100),
                ),
                (
                    "shipping_state",
                    models.CharField(default="Not Provided", max_length=100),
                ),
                (
                    "shipping_postal_code",
                    models.CharField(default="Not Provided", max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="users.subjectmember",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("product_name_snapshot", models.CharField(default="", max_length=255)),
                (
                    "product_price_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("product_image_url_snapshot", models.URLField(blank=True, default="")),
                ("quantity", models.PositiveIntegerField()),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
