# Generated by Django 5.2.7 on 2026-03-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tenant",
            field=models.CharField(default="default_tenant", max_length=100),
        ),
    ]
