# Generated by Django 5.2.7 on 2026-02-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_customer_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_house_no',
            field=models.CharField(default='Not Provided', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_landmark',
            field=models.CharField(default='Not Provided', max_length=20),
        ),
    ]
