# Generated by Django 5.2.5 on 2026-01-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_number_order_user_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
