# Generated by Django 5.2.7 on 2026-03-13 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notifications", "0001_initial"),
        ("orders", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailnotification",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
        migrations.AddField(
            model_name="emailnotification",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="payments.orderpayment"
            ),
        ),
        migrations.AddConstraint(
            model_name="emailnotification",
            constraint=models.UniqueConstraint(
                fields=("event", "order", "payment"),
                name="uniq_order_paid_email_per_payment",
            ),
        ),
    ]
